language: nix
nix: 2.1
sudo: true
matrix:
  include:
    - name: cargo pedantry
      script: nix-shell --run checkPhase -A mozilla-rust-overlay
    - name: checkPhase
      script: nix-shell --run checkPhase
    - name: nix-build
      script: nix-build ./default.nix -A ofborg.rs -A ofborg.php
