[workspace]
members = [
    "ofborg",
    "ofborg-simple-build",
    "ofborg-one-off-build"
]

[profile.release]
debug = true

[patch.crates-io]
#hubcaps = { path = "../hubcaps" }
#amq-proto = { path = "rust-amq-proto" }
