[package]
name = "ofborg"
version = "0.1.8"
authors = ["Graham Christensen <graham@grahamc.com>"]
include = ["Cargo.toml", "Cargo.lock", "src", "test-srcs", "build.rs"]
build = "build.rs"
edition = "2018"

[dependencies]
either = "1.4.0"
log = "= 0.3.8"
env_logger = "= 0.4.3"
# amqp = { path = "./rust-amqp/" } # for testing patches
amqp = { git = "https://github.com/grahamc/rust-amqp.git" }
md5 = "0.3.5"
uuid = { version = "0.4", features = ["v4"] }
fs2 = "0.4.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tempfile = "2.2.0"
hubcaps = { git = "https://github.com/grahamc/hubcaps.git" }
#hubcaps = { path = "../../../grahamc/hubcaps/" } # for testing patches
hyper = "0.10.*"
hyper-native-tls = "0.2.4"
lru-cache = "0.1.1"
nom = "4.0.0-beta3"
sys-info = "0.5.6"
chrono = "0.4.6"
separator = "0.4.1"
