[package]
name = "ofborg-simple-build"
version = "0.1.0"
authors = ["Daiderd Jordan <daiderd@gmail.com>"]
include = ["Cargo.toml", "ofborg-simple-build"]  # TODO remove when carnix is fixed
edition = "2018"

[dependencies]
ofborg = { path = "../ofborg" }

log = "0.3.8"
